openapi: 3.0.1
info:
  title: lessonAPi
  description: lessonAPi
  version: '0.1'

servers:
  - url: http://localhost:8080/tutor-schedule
paths:
  /lessons:

    post:
      description: AssignLesson
      operationId: assignLesson
      requestBody:
        $ref: '#/components/requestBodies/LessonRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  example:
                    $ref: '#/components/responses/LessonResponse'
        '201':
          $ref: '#/components/responses/Created'
        '409':
          $ref: '#/components/responses/Conflict'

    delete:
      parameters:
        - in: header
          name: studentId
          required: true
          schema:
            type: string
            format: uuid
            minimum: 1

        - in: query
          name: lessonId
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1

      description: Remove lesson
      operationId: removeLesson
      responses:
        '200':
          description: Teacher subjects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatesToRemove'
        '404':
          $ref: '#/components/responses/NotFound'

  /lessons/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
    get:
      description: get student lessons
      operationId: getStudentLessons
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  example:
                    $ref: '#/components/responses/LessonResponse'
        '201':
          $ref: '#/components/responses/Created'
        '409':
          $ref: '#/components/responses/Conflict'

  /lessons/changeLessonDate/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1

      - in: query
        name: date
        required: true
        schema:
          type: string
          format: date-time
          description: date of lesson
          example: "2021-06-19 16:00:00"

    delete:
      description: Delete teacher subject
      operationId: deleteTeacherSubject
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'

components:

  requestBodies:
    LessonRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              subject:
                type: string
                enum:
                  - MATHEMATICS
                  - BIOLOGY
              teacherEmail:
                type: string
              teacherFirstName:
                type: string
              teacherLastName:
                type: string
              dateOfLesson:
                type: string
                format: date-time
                description: date of lesson
                example: "2021-06-19 16:00:00"
          examples:
            '0':
              $ref: '#/components/examples/Lesson'

  examples:

    Lesson:
      value:
        {
          "subject": "MATHEMATICS",
          "teacherEmail": "jurek.jurkiewicz@gmail.com",
          "teacherFirstName": "Jurek",
          "teacherLastName": "Jurkiewicz",
          "dateOfLesson": "2012-12-12 16:00:00"
        }

  schemas:

    Status:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

    DatesToRemove:
      type: array
      items:
        format: date-time
        example: "2021-06-19 16:30:00"


  responses:
    LessonResponse:
      description: LessonResponse
      content:
        application/json:
          schema:
            type: object
            properties:
              subject:
                type: string
                enum:
                  - MATHEMATICS
                  - BIOLOGY
              teacherEmail:
                type: string
              teacherFirstName:
                type: string
              teacherLastName:
                type: string
              dateOfLesson:
                type: string
                format: date-time
                description: date of lesson
                example: "2021-06-19 16:00:00"
          examples:
            '0':
              $ref: '#/components/examples/Lesson'

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'

    Created:
      description: Created new Teacher
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'

    Conflict:
      description: Teacher already exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'

    Ok:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'

    NotFound:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'
